FROM denoland/deno:distroless-1.23.3
COPY pterodactyl.js pterodactyl.js
COPY pterodactyl_execute.js pterodactyl_execute.js
COPY test-cases/constantInput/workflow.js test-cases/constantInput/workflow.js
COPY src src
