FROM denoland/deno:distroless-1.23.3
COPY pterodactyl.js pterodactyl.js
COPY pterodactyl_execute.js pterodactyl_execute.js
COPY test-cases/multiworkflowFile/workflows.js test-cases/multiworkflowFile/workflows.js
COPY src src
