FROM denoland/deno:distroless-1.21.0
COPY test-cases/uses-secret/workflow.js test-cases/uses-secret/workflow.js
COPY pterodactyl.js pterodactyl.js
COPY src src
COPY pterodactyl_execute.js pterodactyl_execute.js
