FROM denoland/deno:distroless-1.21.0
COPY test-cases/arrowFuncTask/workflow.js test-cases/arrowFuncTask/workflow.js
COPY pterodactyl.js pterodactyl.js
COPY pterodactyl_execute.js pterodactyl_execute.js
COPY src/ src/
