FROM denoland/deno:distroless-1.21.0
COPY test-cases/arrowFuncTask/success.js test-cases/arrowFuncTask/success.js
COPY pterodactyl.js pterodactyl.js
COPY pterodactyl_execute.js pterodactyl_execute.js
COPY src/ src/
